
name: Using matrix strategy

on: [workflow_dispatch]

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pet: [cat, dog]
        color: [pink, brown]
        age: [1, 4]
        include:
          - color: white
            age: 4
            pet: dog
    steps:
      - run: echo "Hello ${{ matrix.color }} ${{ matrix.pet }}, ${{ matrix.age }} yo"