
name: Using matrix strategy

on: [workflow_dispatch]

jobs:
  development:
    environment: development
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pet: [cat, dog]
        age: [1, 4]
        color: [pink, brown]
        include:
          - pet: dog
            age: 4
            color: brown 
            poil: long
    steps:
      - run: echo "Hello ${{ matrix.color }} ${{ matrix.pet }}, ${{ matrix.age }} yo"
      
  production:
    environment: production
    needs: development
    runs-on: ubuntu-latest 
    steps: 
      - run: echo "Production is done !"